version: '3.8'

services:
  minecraft-bedrock:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft-bedrock
    ports:
      - "19132:19132/udp"  # Порт для Minecraft Bedrock
    volumes:
      - ./data:/data
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      VIEW_DISTANCE: 8
      MAX_THREADS: 0
    restart: always

